from datetime import datetime, timedelta
from typing import Optional
from jose import JWTError, jwt
from passlib.context import CryptContext
import secrets
import os
from sqlalchemy.orm import Session
from app.models import User
from fastapi import Depends, HTTPException, status

# --- CONFIGURATION ---
SECRET_KEY = os.getenv("SECRET_KEY", "a_very_secret_key_that_should_be_in_env")
ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES = 30

pwd_context = CryptContext(schemes=["bcrypt"], deprecated="auto")

# --- PASSWORD UTILS ---
def verify_password(plain_password, hashed_password):
    return pwd_context.verify(plain_password, hashed_password)

def get_password_hash(password):
    return pwd_context.hash(password)

# --- TOKEN UTILS ---
def create_access_token(data: dict, expires_delta: Optional[timedelta] = None):
    to_encode = data.copy()
    if expires_delta:
        expire = datetime.utcnow() + expires_delta
    else:
        expire = datetime.utcnow() + timedelta(minutes=15)
    to_encode.update({"exp": expire})
    encoded_jwt = jwt.encode(to_encode, SECRET_KEY, algorithm=ALGORITHM)
    return encoded_jwt

# --- AUTHENTICATION ---
def get_current_user(db: Session, token: str):
    credentials_exception = HTTPException(
        status_code=status.HTTP_401_UNAUTHORIZED,
        detail="Invalid authentication credentials",
        headers={"WWW-Authenticate": "Bearer"},
    )
    try:
        payload = jwt.decode(token, SECRET_KEY, algorithms=[ALGORITHM])
        email: str = payload.get("sub")
        if email is None:
            raise credentials_exception
    except JWTError:
        raise credentials_exception
    
    user = db.query(User).filter(User.email == email).first()
    
    if user is None:
        raise credentials_exception
    return user

# --- CODE GENERATION ---
def generate_verification_code(length=6):
    return "".join(secrets.choice("0123456789") for _ in range(length))

def generate_reset_code(length=6):
    return "".join(secrets.choice("0123456789") for _ in range(length))

from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import get_openapi_examples
from fastapi.openapi.utils import get_openapi_parameters
from fastapi.openapi.utils import get_openapi_document
from fastapi.openapi.utils import get_openapi_info
from fastapi.openapi.utils import get_openapi_tags
from fastapi.openapi.docs import get_openapi_description
from fastapi.openapi.utils import get_openapi_schemas
from fastapi.openapi.utils import get_openapi_responses
from fastapi.openapi.utils import